spring:
  config:
    activate:
      on-profile: windows
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    url: jdbc:mariadb://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123123
    hikari:
      pool-name: HikariPool
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000


server:
  port: 80
  ssl:
    enabled: false
    key-store: classpath:ssl/keystore.p12
    key-store-password: 123123